---
title: "report"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(janitor)
```


```{r}
raw <- read_excel('./datasets/covid-daily.xlsx', sheet=1)
```

```{r}
names(raw) <- c("idx", "loc_firstid", "f_to0",
                   "case0", "case_direct", "contact_loc", "contact_loc_dis",
                   "contact_loc_com", "contact_lastdate", "contact_type", "rel_to_case_direct",
                   "date_report", "date_public",
                   "id", "name", "id_name", "yob", "sex",
                   "national", "passport", "tel", "email",
                   "job", "job_loc", "job_loc_block", "job_loc_floor", "job_loc_room",
                   "job_loc_pro", "job_loc_dis", "job_loc_com",
                   "trans_seatnum",
                   "res_loc", "res_loc_block", "res_loc_floor", "res_loc_room",
                   "res_loc_pro", "res_loc_dis", "res_loc_com",
                   "qrt_type", "qrt_pro", "qrt_dis", "qrt_name", "qrt_date",
                   "test_01_taken", "test_01_who_taken", "test_01_who_proc", "test_01_date_taken",
                   "test_01_result", "test_01_date_result",
                   "test_02_taken", "test_02_who_taken", "test_02_who_proc", "test_02_date_taken",
                   "test_02_result", "test_02_date_result",
                   "test_03_taken", "test_03_who_taken", "test_03_who_proc", "test_03_date_taken",
                   "test_03_result", "test_03_date_result",
                   "test_04_taken", "test_04_who_taken", "test_04_who_proc", "test_04_date_taken",
                   "test_04_result", "test_04_date_result",
                   "test_05_taken", "test_05_who_taken", "test_05_who_proc", "test_05_date_taken",
                   "test_05_result", "test_05_date_result",
                   "local_confirmed", "note", "test_ab_date", "test_ab_result", "student",
                   "clin_symptoms", "clin_date_onset", "clin_prog", "clin_fever",
                   "clin_cough", "clin_sneeze", "clin_sore", "clin_chest", "clin_breath",
                   "clin_tastelost", "clin_smelllost", "clin_chills", "clin_tired", "clin_other",
                   "CT_test_pos", "contact_loc2", "invest_form", "test_date", "qrt_date_in", "f0_loc", "loc")
```

